apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-container-deployment
  labels: 
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: spark-container-pod
        image: ckooram/containerized-spark:latest
        ports:
          - containerPort: 80
