apiVersion: v1
kind: Pod
metadata:
  name: spark-container
  labels: 
    app: web
spec:
  containers:
    - name: spark-container
      image: ckooram/containerized-spark:latest
      ports:
        - containerPort: 80
        
